version: "3"
services:

  mongodb-server:
    image: mongo
    container_name: 'customerapi-mongo-server'
    restart: always
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd123      
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
