version: "3"
services:

  postgresql-server:
    image: postgres:alpine
    container_name: 'microservice-identitydb-test-server'
    restart: always
    ports:
      - 5433:5432 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: microSERVICE          
    networks:
      - webnet 

networks:
  webnet: