version: "3"
services:

  # Setup Postgres DB for microSERVICE application 
  postgresql-server:
    image: postgres:alpine
    container_name: 'microservice-pgsql-server'
    restart: always
    ports:
      - 5433:5432 
    volumes:
      - ./../data/postgres/db:/var/lib/postgresql/data
      - ./../data/postgres/logs:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: microSERVICE   
      PGDATA: /var/lib/postgresql/data/pgdata       
    networks:      
      - microservices-frontend      

networks:
  microservices-frontend:
    driver: bridge
